language: node_js
node_js:
- '12'
install:
- npm install
- npm build
script: skip
deploy:
  provider: heroku
  app:
    deploy: nooblovers-teamo
    master: nooblovers-teamo-master
  api_key:
    secure: JKND5++6ZcIp8xy7ZiGvayKu7iI7h335uYAB8zOOxo1V/XyulCMw2Vu8HKGV5dn0P2x71IYxG8sZS6YfEb2FWps+Kj4EoqA7sNT4R3eZkDCK6mfo3/iy9OtSZQhJV0GU5fvzQlvEr/yhBR+QT2AxO81JqY7mWbi4CxmlSx+IrSQpIv5DMCu63gSmIpD1IX61rLiEzCRLF8BKN+5vMFZpkeDE/7ECP2AN9H13rADy6Obg6wjcKdItauT0lEk7npTvMroka92VNF0m1FAGnxrDJOpesWh6x8YYAa4w2v+XAAm2Sp1TxhKvFUXGy7u3Z760zF6qGGsagS8klb3kwPikjvMJ0u0lD25kZ6Zmn1B4b6etK656UfHHk3N+3TsT9C1XomIjA1OtBBEN6G/DzDrHi5QnXrWIscjhwikqepsnocWPWXjKO8Y9fqfSO9voqo/yfbv4GJeJRgzlOiXpN4WWpddgckKvkoNiZp4Nt30bU0cPLLHXJkSCGBYl47TCryQK7e6iSWhDGhe8F9AdfTIbQ/BPPgIGHmG8XByf4W4VcR3qKXlMwNF2SoW9jV6F9PWyWz+Gh2+CwuNgPYFl9Y/3D6LGF+2PbeBQRi/dm/U6WCr6iXF0Jf6+Hk5F0y/PVvtY89c8mnb7oYilkewOWC+ne6FkS0/7RJGGiP4PAQDIB7g=
