name: Build and deploy Teamo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        # npm test
    - uses: rlespinasse/github-slug-action@1.1.0
    - name: Print ref
      if: startsWith(github.ref, 'refs/tags')
      run: echo I am a tag with slug ${{env.GITHUB_REF_SLUG}}
    - name: Print branch
      if: startsWith(github.ref, 'refs/heads') && endsWith(github.ref, 'feature/github-actions')
      run: echo I am a branch with slug ${{env.GITHUB_REF_SLUG}}
    # - name: deploy
    #   run: |
    #     openssl aes-256-cbc -K $encrypted_ac2413816663_key -iv $encrypted_ac2413816663_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
    #     eval "$(ssh-agent -s)"
    #     chmod 600 /tmp/deploy_rsa
    #     ssh-add /tmp/deploy_rsa
    #     bash deploy.sh
